---
- name: Test Azure
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    res_group: lab

  pre_tasks:
    - name: Validate that we have a lab_id
      assert:
          that: lab_id is defined 
          msg: You need to pass lab_id as an extra parameter to execute this playbook
    
    - name: Do we have our AZURE Credentials
      assert:
        { that: "{{ item}} != ''" }
      with_items:
        - azure_client_id
        - azure_tenant
        - azure_subscription_id
        - azure_secret 
  tasks:
    - name: Delete test resource group
      azure_rm_resourcegroup:
        client_id: "{{ azure_client_id }}"
        tenant: "{{ azure_tenant }}"
        subscription_id: "{{ azure_subscription_id }}"
        secret: "{{ azure_secret }}"
        state: absent
        name: "{{ res_group }}"
